name = "notion-task-creator"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
NOTION_DATABASE_ID = "699e5cdc-742a-4c17-89e2-ef27f169cd0e"
HERMES_BASE_URL = "http://hermeswebhook.delianpetrov.com"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
